### ISSUE TITLE
Highlight only 3rd-party visited links

### ISSUE THREAD

**Issue by AlttiRi** [AlttiRi/twitter-click-and-save#14]
Highlight only _3rd-party_ visited links. Optionally.

Seems
```css
                a[href^="http"]:visited {
                    color: darkorange;
                }
```
will be enough.
